# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9843d6abed350cec7a8a51ba2f934b3a4ceceb91b693eca95fd5dfd5e7550d9f75362d718ded0d9c7ecb271a43edb2444de8272b1958a6568985e5143a8740a4

test:
  secret_key_base: 8b61bc6c4d772215460e5a825b636c42deff982d556a22bccd21ad72f4f7f12a0a9d499bc61a18d6c60ae1fda7b9e7bd336e4e11205e20107e6d1fd36e55685e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
